seed: 42

reproducibility:
  seed: 42

data:
  train_dir: "/mnt/zzbnew/rnamodel/zhoukexuan/PoreDLM/data/DNA_modifiction/without_modifiction/stage2_BERT_Encoder/train/train"
  valid_dir: "/mnt/zzbnew/rnamodel/zhoukexuan/PoreDLM/data/DNA_modifiction/without_modifiction/stage2_BERT_Encoder/validation/validation"
  num_workers: 8
  prefetch_factor: 2
  pin_memory: true
  max_cache_size: 32

model:
  # Stage 1 codebook ids are 0..8195. 加上129个token，再加一个Reserve 65536 as the BERT [MASK] id.
  tokenizer_path: "/mnt/zzbnew/rnamodel/zhoukexuan/PoreDLM/src/poredlm/data/stage2_BERT_Encoder/tokenizer-8k.json"
  vocab_size: 8325
  mask_token_id: 4
  pad_token_id: 1
  unk_token_id: 0
  random_token_min_id: 129
  random_token_max_id: 8325
  hidden_size: 768
  num_hidden_layers: 4
  num_attention_heads: 8
  intermediate_size: 3072
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 4096
  mask_probability: 0.15

training:
  max_steps: 200000
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_steps: 1000
  lr_scheduler_type: cosine
  device_micro_batch_size: 32
  gradient_accumulation_steps: 1
  mixed_precision: "no"
  gradient_clipping: 1.0
  output_dir: "models/stage2_BERT_Encoder"
  log_dir: "log"
  log_every_steps: 10
  eval_every_steps: 1000
  max_eval_batches: 100
  save_every_steps: 50000

wandb:
  use_wandb: True
  project: "stage2_BERT_Encoder_experiments"
  name: "test-zhou-stage2-bert"
