"""Train Stage 2 BERT on token shards generated by token_dataset/infer.py."""

from __future__ import annotations

import argparse
import math
import os
import random
import shutil
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml
from accelerate import Accelerator
from torch.optim import AdamW
from torch.optim.lr_scheduler import LambdaLR
from torch.utils.data import DataLoader
from tqdm.auto import tqdm

from modeling_stage2_bert import Stage2BertConfig, Stage2MaskedSignalLM
from token_memmap_dataset import TokenMemmapIterableDataset


def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def mask_token_ids(
    input_ids: torch.Tensor,
    attention_mask: torch.Tensor,
    vocab_size: int,
    mask_token_id: int,
    mask_probability: float,
    random_token_min_id: int,
    random_token_max_id: int,
) -> tuple[torch.Tensor, torch.Tensor]:
    labels = input_ids.clone()
    probability = torch.full(labels.shape, float(mask_probability), device=input_ids.device)
    probability = probability.masked_fill(attention_mask == 0, 0.0)
    masked_indices = torch.bernoulli(probability).bool()
    labels[~masked_indices] = -100

    corrupted = input_ids.clone()
    replace_with_mask = torch.bernoulli(torch.full(labels.shape, 0.8, device=input_ids.device)).bool()
    corrupted[masked_indices & replace_with_mask] = int(mask_token_id)

    replace_with_random = (
        torch.bernoulli(torch.full(labels.shape, 0.5, device=input_ids.device)).bool()
        & masked_indices
        & ~replace_with_mask
    )
    random_token_max_id = min(int(random_token_max_id), int(vocab_size))
    random_ids = torch.randint(
        low=int(random_token_min_id),
        high=random_token_max_id,
        size=labels.shape,
        dtype=input_ids.dtype,
        device=input_ids.device,
    )
    corrupted[replace_with_random] = random_ids[replace_with_random]
    return corrupted, labels


def build_scheduler(optimizer: torch.optim.Optimizer, name: str, warmup_steps: int, total_steps: int) -> LambdaLR:
    warmup_steps = max(0, int(warmup_steps))
    total_steps = max(1, int(total_steps))
    scheduler_name = str(name).lower()

    def lr_lambda(step: int) -> float:
        if warmup_steps and step < warmup_steps:
            return float(step) / float(max(1, warmup_steps))
        progress = float(step - warmup_steps) / float(max(1, total_steps - warmup_steps))
        progress = min(max(progress, 0.0), 1.0)
        if scheduler_name == "cosine":
            return 0.5 * (1.0 + math.cos(math.pi * progress))
        if scheduler_name == "linear":
            return max(0.0, 1.0 - progress)
        if scheduler_name in {"constant", "constant_with_warmup"}:
            return 1.0
        raise ValueError(f"Unsupported lr_scheduler_type={name!r}.")

    return LambdaLR(optimizer, lr_lambda)


def build_loader(config: dict[str, Any], split: str) -> DataLoader:
    data_cfg = config["data"]
    model_cfg = config["model"]
    training_cfg = config["training"]
    data_dir = data_cfg.get(f"{split}_dir")
    if not data_dir:
        raise ValueError(f"Missing data.{split}_dir.")
    dataset = TokenMemmapIterableDataset(
        data_dir=data_dir,
        pattern=str(data_cfg.get("file_pattern", "*.npy")),
        token_dtype=str(data_cfg.get("token_dtype", "uint32")),
        max_length=int(model_cfg.get("max_position_embeddings", 1280)),
        pad_token_id=int(model_cfg.get("pad_token_id", 0)),
        shuffle_files=bool(data_cfg.get(f"{split}_shuffle_files", split == "train")),
        seed=int(config.get("reproducibility", {}).get("seed", config.get("seed", 42))),
        repeat=(split == "train"),
    )
    num_workers = int(data_cfg.get("num_workers", 4))
    loader_kwargs: dict[str, Any] = {
        "batch_size": int(training_cfg.get("device_micro_batch_size", 8)),
        "shuffle": False,
        "num_workers": num_workers,
        "pin_memory": bool(data_cfg.get("pin_memory", True)),
        "drop_last": split == "train",
    }
    if num_workers > 0:
        loader_kwargs["prefetch_factor"] = int(data_cfg.get("prefetch_factor", 2))
        loader_kwargs["persistent_workers"] = bool(data_cfg.get("persistent_workers", True))
    return DataLoader(dataset, **loader_kwargs)


def build_model(config: dict[str, Any]) -> Stage2MaskedSignalLM:
    model_cfg = config["model"]
    hf_path = model_cfg.get("init_from_pretrained")
    if hf_path:
        return Stage2MaskedSignalLM.from_pretrained(hf_path)

    hf_config = Stage2BertConfig(
        vocab_size=int(model_cfg.get("vocab_size", 65664)),
        hidden_size=int(model_cfg.get("hidden_size", 768)),
        num_hidden_layers=int(model_cfg.get("num_hidden_layers", 12)),
        num_attention_heads=int(model_cfg.get("num_attention_heads", 12)),
        intermediate_size=int(model_cfg.get("intermediate_size", 3072)),
        hidden_dropout_prob=float(model_cfg.get("hidden_dropout_prob", 0.1)),
        attention_probs_dropout_prob=float(model_cfg.get("attention_probs_dropout_prob", 0.1)),
        max_position_embeddings=int(model_cfg.get("max_position_embeddings", 1280)),
        pad_token_id=int(model_cfg.get("pad_token_id", 0)),
        mask_token_id=int(model_cfg.get("mask_token_id", 1)),
    )
    return Stage2MaskedSignalLM(hf_config)


def save_hf_checkpoint(
    accelerator: Accelerator,
    model: torch.nn.Module,
    output_dir: str | os.PathLike[str],
    step_name: str,
    global_step: int,
    config: dict[str, Any],
) -> None:
    accelerator.wait_for_everyone()
    if not accelerator.is_main_process:
        return

    save_dir = Path(output_dir) / str(step_name)
    save_dir.mkdir(parents=True, exist_ok=True)
    unwrapped = accelerator.unwrap_model(model)
    unwrapped.config.architectures = ["Stage2MaskedSignalLM"]
    unwrapped.config.auto_map = {
        "AutoConfig": "modeling_stage2_bert.Stage2BertConfig",
        "AutoModel": "modeling_stage2_bert.Stage2MaskedSignalLM",
        "AutoModelForMaskedLM": "modeling_stage2_bert.Stage2MaskedSignalLM",
    }
    unwrapped.save_pretrained(save_dir, safe_serialization=True)
    shutil.copy2(Path(__file__).with_name("modeling_stage2_bert.py"), save_dir / "modeling_stage2_bert.py")
    with (save_dir / "training_config.yaml").open("w", encoding="utf-8") as handle:
        yaml.safe_dump(config, handle, sort_keys=False, allow_unicode=True)
    torch.save({"global_step": int(global_step), "model_format": "hf_pretrained"}, save_dir / "trainer_state.pt")

    latest_dir = Path(output_dir) / "latest"
    if latest_dir.exists() or latest_dir.is_symlink():
        if latest_dir.is_symlink() or latest_dir.is_file():
            latest_dir.unlink()
        else:
            shutil.rmtree(latest_dir)
    shutil.copytree(save_dir, latest_dir)


def evaluate(
    accelerator: Accelerator,
    model: torch.nn.Module,
    valid_loader: DataLoader,
    config: dict[str, Any],
) -> dict[str, float]:
    model.eval()
    model_cfg = config["model"]
    training_cfg = config["training"]
    max_eval_batches = training_cfg.get("max_eval_batches")
    max_eval_batches = int(max_eval_batches) if max_eval_batches is not None else None

    total_loss = torch.zeros((), device=accelerator.device)
    total_masked = torch.zeros((), device=accelerator.device)
    total_correct = torch.zeros((), device=accelerator.device)
    total_batches = torch.zeros((), device=accelerator.device)

    with torch.no_grad():
        for batch_idx, batch in enumerate(valid_loader):
            if max_eval_batches is not None and batch_idx >= max_eval_batches:
                break
            input_ids = batch["input_ids"].to(accelerator.device)
            attention_mask = batch["attention_mask"].to(accelerator.device)
            corrupted, labels = mask_token_ids(
                input_ids=input_ids,
                attention_mask=attention_mask,
                vocab_size=int(model_cfg["vocab_size"]),
                mask_token_id=int(model_cfg["mask_token_id"]),
                mask_probability=float(model_cfg.get("mask_probability", 0.15)),
                random_token_min_id=int(model_cfg.get("random_token_min_id", 4)),
                random_token_max_id=int(model_cfg.get("random_token_max_id", model_cfg["vocab_size"])),
            )
            outputs = model(input_ids=corrupted, attention_mask=attention_mask, labels=labels)
            masked = labels != -100
            masked_count = masked.sum()
            total_masked += masked_count
            total_loss += outputs.loss.detach() * masked_count.clamp_min(1)
            if masked_count.item() > 0:
                total_correct += (outputs.logits.argmax(dim=-1)[masked] == labels[masked]).sum()
            total_batches += 1

    totals = accelerator.gather_for_metrics(
        torch.stack([total_loss, total_masked, total_correct, total_batches]).unsqueeze(0)
    ).sum(dim=0)
    model.train()

    loss = (totals[0] / totals[1].clamp_min(1)).item()
    masked_tokens = totals[1].item()
    return {
        "eval/loss": loss,
        "eval/perplexity": math.exp(loss) if loss < 50 else float("inf"),
        "eval/top1_accuracy": (totals[2] / totals[1].clamp_min(1)).item(),
        "eval/masked_tokens": masked_tokens,
        "eval/batches": totals[3].item(),
    }


def train(config: dict[str, Any]) -> None:
    seed = int(config.get("reproducibility", {}).get("seed", config.get("seed", 42)))
    seed_everything(seed)

    training_cfg = config["training"]
    model_cfg = config["model"]
    accelerator = Accelerator(
        gradient_accumulation_steps=int(training_cfg.get("gradient_accumulation_steps", 1)),
        mixed_precision=str(training_cfg.get("mixed_precision", "no")),
        log_with="wandb" if config.get("wandb", {}).get("use_wandb", False) else None,
        project_dir=str(training_cfg.get("log_dir", "log")),
    )

    train_loader = build_loader(config, "train")
    valid_loader = build_loader(config, "valid") if config["data"].get("valid_dir") else None
    model = build_model(config)
    optimizer = AdamW(
        model.parameters(),
        lr=float(training_cfg.get("learning_rate", 5e-4)),
        weight_decay=float(training_cfg.get("weight_decay", 0.01)),
    )
    max_train_steps = int(training_cfg["max_train_steps"])
    scheduler_steps = int(training_cfg.get("scheduler_num_training_steps", max_train_steps))
    scheduler = build_scheduler(
        optimizer,
        name=str(training_cfg.get("lr_scheduler_type", "cosine")),
        warmup_steps=int(training_cfg.get("warmup_steps", 1000)),
        total_steps=scheduler_steps,
    )

    if config.get("wandb", {}).get("use_wandb", False):
        accelerator.init_trackers(
            project_name=str(config["wandb"].get("project", "poredlm-stage2-bert")),
            config=config,
            init_kwargs={"wandb": {"name": config["wandb"].get("name")}},
        )

    if valid_loader is not None:
        model, optimizer, scheduler, train_loader, valid_loader = accelerator.prepare(
            model, optimizer, scheduler, train_loader, valid_loader
        )
    else:
        model, optimizer, scheduler, train_loader = accelerator.prepare(model, optimizer, scheduler, train_loader)

    output_dir = str(training_cfg.get("output_dir", "models"))
    log_every = int(training_cfg.get("log_every_steps", 10))
    save_every = int(training_cfg.get("save_every_steps", 1000))
    eval_every = int(training_cfg.get("eval_every_steps", 0))
    global_step = 0
    progress = tqdm(total=max_train_steps, disable=not accelerator.is_local_main_process)
    model.train()

    while global_step < max_train_steps:
        for batch in train_loader:
            if global_step >= max_train_steps:
                break
            with accelerator.accumulate(model):
                input_ids = batch["input_ids"].to(accelerator.device)
                attention_mask = batch["attention_mask"].to(accelerator.device)
                corrupted, labels = mask_token_ids(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    vocab_size=int(model_cfg["vocab_size"]),
                    mask_token_id=int(model_cfg["mask_token_id"]),
                    mask_probability=float(model_cfg.get("mask_probability", 0.15)),
                    random_token_min_id=int(model_cfg.get("random_token_min_id", 4)),
                    random_token_max_id=int(model_cfg.get("random_token_max_id", model_cfg["vocab_size"])),
                )
                outputs = model(input_ids=corrupted, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                accelerator.backward(loss)
                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(model.parameters(), float(training_cfg.get("gradient_clipping", 1.0)))
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()

            if accelerator.sync_gradients:
                global_step += 1
                progress.update(1)
                if global_step % log_every == 0:
                    loss_value = accelerator.gather_for_metrics(loss.detach()).mean().item()
                    logs = {
                        "train/loss": loss_value,
                        "train/lr": scheduler.get_last_lr()[0],
                        "step": global_step,
                    }
                    accelerator.log(logs, step=global_step)
                    if accelerator.is_main_process:
                        print(logs, flush=True)

                if valid_loader is not None and eval_every > 0 and global_step % eval_every == 0:
                    eval_logs = evaluate(accelerator, model, valid_loader, config)
                    eval_logs["step"] = global_step
                    accelerator.log(eval_logs, step=global_step)
                    if accelerator.is_main_process:
                        print(eval_logs, flush=True)

                if save_every > 0 and global_step % save_every == 0:
                    save_hf_checkpoint(accelerator, model, output_dir, f"step_{global_step}", global_step, config)

    save_hf_checkpoint(accelerator, model, output_dir, "final", global_step, config)
    progress.close()
    accelerator.end_training()


def main() -> None:
    parser = argparse.ArgumentParser(description="Train Stage 2 BERT from infer.py token memmaps.")
    parser.add_argument("--config", type=str, required=True)
    args = parser.parse_args()
    with open(args.config, "r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle)
    train(config)


if __name__ == "__main__":
    main()
